networks:
    1panel-network:
        external: true

services:
  sdk-server-c294def:
    build: .
    container_name: sdk-server-c294def
    volumes:
      - ./sdk_server:/home/sdk_server  # 挂载本地目录到容器
    working_dir: /home/sdk_server
    command: python manage.py
    env_file:
      - ./.env
    restart: unless-stopped
    ports:
      - "5000:80" # 将容器的80端口映射到主机的5000端口
    networks:
      - 1panel-network
    