

services:



  sdk-server-c294def:
    build: .
    container_name: sdk-server-c294def
    volumes:
      - ./sdk_server:/home/sdk_server  # 挂载本地目录到容器
    working_dir: /home/sdk_server
    command: python manage.py
    restart: unless-stopped
    ports:
      - "5000:80"
      - "20022:22"
    env_file:
      - ./.env