# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: resume.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='resume.proto',
  package='corasdk_resume',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cresume.proto\x12\x0e\x63orasdk_resume\"\xec\x01\n\x0cPersonalInfo\x12\r\n\x05\x62irth\x18\x01 \x01(\t\x12\x0e\n\x06school\x18\x02 \x01(\t\x12\x11\n\teducation\x18\x03 \x01(\t\x12\r\n\x05major\x18\x04 \x01(\t\x12\x14\n\x0cnative_place\x18\x05 \x01(\t\x12\x15\n\rcurrent_place\x18\x06 \x01(\t\x12\r\n\x05\x65mail\x18\x07 \x01(\t\x12\r\n\x05phone\x18\x08 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\t \x01(\t\x12\x0f\n\x07\x63ontent\x18\n \x01(\t\x12\r\n\x05label\x18\x0b \x01(\t\x12\x0c\n\x04name\x18\x0c \x01(\t\x12\x11\n\tphoto_url\x18\r \x01(\t\"M\n\tEducation\x12\x0e\n\x06\x64\x65gree\x18\x01 \x01(\t\x12\r\n\x05major\x18\x02 \x01(\t\x12\x13\n\x0bschool_name\x18\x03 \x01(\t\x12\x0c\n\x04time\x18\x04 \x01(\t\"?\n\x0bProjectWork\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\twork_time\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\"4\n\x12SkillsIntroduction\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"%\n\x07TagList\x12\x0c\n\x04icon\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"a\n\x0eWorkExperience\x12\x14\n\x0c\x63ompany_name\x18\x01 \x01(\t\x12\x10\n\x08position\x18\x02 \x01(\t\x12\x11\n\twork_time\x18\x03 \x01(\t\x12\x14\n\x0cwork_content\x18\x04 \x01(\t\"\xc7\x02\n\x06Resume\x12\x33\n\rpersonal_info\x18\x01 \x01(\x0b\x32\x1c.corasdk_resume.PersonalInfo\x12-\n\neducations\x18\x02 \x03(\x0b\x32\x19.corasdk_resume.Education\x12\x32\n\rproject_works\x18\x03 \x03(\x0b\x32\x1b.corasdk_resume.ProjectWork\x12?\n\x13skills_introduction\x18\x04 \x01(\x0b\x32\".corasdk_resume.SkillsIntroduction\x12*\n\ttag_lists\x18\x05 \x03(\x0b\x32\x17.corasdk_resume.TagList\x12\x38\n\x10work_experiences\x18\x06 \x03(\x0b\x32\x1e.corasdk_resume.WorkExperienceb\x06proto3'
)




_PERSONALINFO = _descriptor.Descriptor(
  name='PersonalInfo',
  full_name='corasdk_resume.PersonalInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='birth', full_name='corasdk_resume.PersonalInfo.birth', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='school', full_name='corasdk_resume.PersonalInfo.school', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='education', full_name='corasdk_resume.PersonalInfo.education', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='major', full_name='corasdk_resume.PersonalInfo.major', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='native_place', full_name='corasdk_resume.PersonalInfo.native_place', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='current_place', full_name='corasdk_resume.PersonalInfo.current_place', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='email', full_name='corasdk_resume.PersonalInfo.email', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='phone', full_name='corasdk_resume.PersonalInfo.phone', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='address', full_name='corasdk_resume.PersonalInfo.address', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content', full_name='corasdk_resume.PersonalInfo.content', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='label', full_name='corasdk_resume.PersonalInfo.label', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='corasdk_resume.PersonalInfo.name', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='photo_url', full_name='corasdk_resume.PersonalInfo.photo_url', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=269,
)


_EDUCATION = _descriptor.Descriptor(
  name='Education',
  full_name='corasdk_resume.Education',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='degree', full_name='corasdk_resume.Education.degree', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='major', full_name='corasdk_resume.Education.major', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='school_name', full_name='corasdk_resume.Education.school_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time', full_name='corasdk_resume.Education.time', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=271,
  serialized_end=348,
)


_PROJECTWORK = _descriptor.Descriptor(
  name='ProjectWork',
  full_name='corasdk_resume.ProjectWork',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='corasdk_resume.ProjectWork.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='work_time', full_name='corasdk_resume.ProjectWork.work_time', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content', full_name='corasdk_resume.ProjectWork.content', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=350,
  serialized_end=413,
)


_SKILLSINTRODUCTION = _descriptor.Descriptor(
  name='SkillsIntroduction',
  full_name='corasdk_resume.SkillsIntroduction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='corasdk_resume.SkillsIntroduction.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content', full_name='corasdk_resume.SkillsIntroduction.content', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=415,
  serialized_end=467,
)


_TAGLIST = _descriptor.Descriptor(
  name='TagList',
  full_name='corasdk_resume.TagList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='icon', full_name='corasdk_resume.TagList.icon', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='corasdk_resume.TagList.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=469,
  serialized_end=506,
)


_WORKEXPERIENCE = _descriptor.Descriptor(
  name='WorkExperience',
  full_name='corasdk_resume.WorkExperience',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='company_name', full_name='corasdk_resume.WorkExperience.company_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='position', full_name='corasdk_resume.WorkExperience.position', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='work_time', full_name='corasdk_resume.WorkExperience.work_time', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='work_content', full_name='corasdk_resume.WorkExperience.work_content', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=508,
  serialized_end=605,
)


_RESUME = _descriptor.Descriptor(
  name='Resume',
  full_name='corasdk_resume.Resume',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='personal_info', full_name='corasdk_resume.Resume.personal_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='educations', full_name='corasdk_resume.Resume.educations', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='project_works', full_name='corasdk_resume.Resume.project_works', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='skills_introduction', full_name='corasdk_resume.Resume.skills_introduction', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tag_lists', full_name='corasdk_resume.Resume.tag_lists', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='work_experiences', full_name='corasdk_resume.Resume.work_experiences', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=608,
  serialized_end=935,
)

_RESUME.fields_by_name['personal_info'].message_type = _PERSONALINFO
_RESUME.fields_by_name['educations'].message_type = _EDUCATION
_RESUME.fields_by_name['project_works'].message_type = _PROJECTWORK
_RESUME.fields_by_name['skills_introduction'].message_type = _SKILLSINTRODUCTION
_RESUME.fields_by_name['tag_lists'].message_type = _TAGLIST
_RESUME.fields_by_name['work_experiences'].message_type = _WORKEXPERIENCE
DESCRIPTOR.message_types_by_name['PersonalInfo'] = _PERSONALINFO
DESCRIPTOR.message_types_by_name['Education'] = _EDUCATION
DESCRIPTOR.message_types_by_name['ProjectWork'] = _PROJECTWORK
DESCRIPTOR.message_types_by_name['SkillsIntroduction'] = _SKILLSINTRODUCTION
DESCRIPTOR.message_types_by_name['TagList'] = _TAGLIST
DESCRIPTOR.message_types_by_name['WorkExperience'] = _WORKEXPERIENCE
DESCRIPTOR.message_types_by_name['Resume'] = _RESUME
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PersonalInfo = _reflection.GeneratedProtocolMessageType('PersonalInfo', (_message.Message,), {
  'DESCRIPTOR' : _PERSONALINFO,
  '__module__' : 'resume_pb2'
  # @@protoc_insertion_point(class_scope:corasdk_resume.PersonalInfo)
  })
_sym_db.RegisterMessage(PersonalInfo)

Education = _reflection.GeneratedProtocolMessageType('Education', (_message.Message,), {
  'DESCRIPTOR' : _EDUCATION,
  '__module__' : 'resume_pb2'
  # @@protoc_insertion_point(class_scope:corasdk_resume.Education)
  })
_sym_db.RegisterMessage(Education)

ProjectWork = _reflection.GeneratedProtocolMessageType('ProjectWork', (_message.Message,), {
  'DESCRIPTOR' : _PROJECTWORK,
  '__module__' : 'resume_pb2'
  # @@protoc_insertion_point(class_scope:corasdk_resume.ProjectWork)
  })
_sym_db.RegisterMessage(ProjectWork)

SkillsIntroduction = _reflection.GeneratedProtocolMessageType('SkillsIntroduction', (_message.Message,), {
  'DESCRIPTOR' : _SKILLSINTRODUCTION,
  '__module__' : 'resume_pb2'
  # @@protoc_insertion_point(class_scope:corasdk_resume.SkillsIntroduction)
  })
_sym_db.RegisterMessage(SkillsIntroduction)

TagList = _reflection.GeneratedProtocolMessageType('TagList', (_message.Message,), {
  'DESCRIPTOR' : _TAGLIST,
  '__module__' : 'resume_pb2'
  # @@protoc_insertion_point(class_scope:corasdk_resume.TagList)
  })
_sym_db.RegisterMessage(TagList)

WorkExperience = _reflection.GeneratedProtocolMessageType('WorkExperience', (_message.Message,), {
  'DESCRIPTOR' : _WORKEXPERIENCE,
  '__module__' : 'resume_pb2'
  # @@protoc_insertion_point(class_scope:corasdk_resume.WorkExperience)
  })
_sym_db.RegisterMessage(WorkExperience)

Resume = _reflection.GeneratedProtocolMessageType('Resume', (_message.Message,), {
  'DESCRIPTOR' : _RESUME,
  '__module__' : 'resume_pb2'
  # @@protoc_insertion_point(class_scope:corasdk_resume.Resume)
  })
_sym_db.RegisterMessage(Resume)


# @@protoc_insertion_point(module_scope)
